### ISSUE TITLE
Bug: Unable to run a build

### ISSUE THREAD

**Issue by dayvod** [projectunic0rn/lit-ui#17]
I merged and ran a yarn run buildto double check that the app can still run smoothly. End up getting a dependency missing error for@babel/transform-react-jsx-source` after installing that dependency I received this error:

jest-haste-map: watch error:
  Error: ENOENT: no such file or directory, open '/lit-ui/node_modules/metro/node_modules/jest-haste-map/build/worker.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Module._extensions..js (module.js:663:20)
    at Object.require.extensions.(anonymous function) [as .js] (/lit-ui/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at _load_worker (/node_modules/metro/node_modules/jest-haste-map/build/index.js:18:20)
I found this as a potential solution:
https://stackoverflow.com/questions/41604983/how-to-resolve-the-jest-haste-map-error-in-react-native

I haven't used it yet, because it involves removing react-native and reinstalling it from our node_modules directory.

I am looking into the issue further and will open a High Priority Bug ticket. Worst case we can always revert back to a previous commit.

**Comment by dayvod** [comment]
For more information see this comment log: 

https://github.com/projectunic0rn/lit-ui/pull/16
